version: 2
aliases:
  - &envinfo
    name: Run envinfo
    command: |
      npx envinfo

jobs:
  ubuntu-test:
    working_directory: ~/repo
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Check Node installation
          command: |
            export DEBIAN_FRONTEND=noninteractive
            bash ./scripts/deb/setup_lts.x
            apt-get install nodejs -y
      - run: *envinfo
  debian-test:
    working_directory: ~/repo
    docker:
      - image: debian
    steps:
      - checkout
      - run:
          name: Check Node installation
          command: |
            bash ./scripts/deb/setup_lts.x
            apt-get install nodejs -y
      - run: *envinfo
  amazonlinux-test:
    working_directory: ~/repo
    docker:
      - image: amazonlinux:2023
    steps:
      - checkout
      - run:
          name: Check Node installation
          environment:
            NODE_MAJOR: 20
          command: |
            bash ./scripts/rpm/setup_lts.x
            yum install nodejs -y
      - run: *envinfo
  fedora-test:
    working_directory: ~/repo
    docker:
      - image: fedora
    steps:
      - checkout
      - run:
          name: Check Node installation
          command: |
            bash ./scripts/rpm/setup_lts.x
            yum install nodejs -y
      - run: *envinfo

workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu-test
      - debian-test
      - amazonlinux-test
      - fedora-test
